### PR TITLE
Use ‘megaparsec-8.0.0’

### PR DESCRIPTION
**Pull request by mrkkrp**

### CODE REVIEW

**Comment by mrkkrp** [comment]
@srid @benkolera Do you know what is going on here? https://travis-ci.org/mmark-md/mmark/jobs/609220664?utm_medium=notification&utm_source=github_status

**Comment by benkolera** [comment]
This is the kind of error that you see when the haskell code is using some C code or a part of the RTS that isn't available in that version of GHCjs. I note that we are still building with ghcjs 8.4, so it may be that. I'll have a look into this later today when I'm not supposed to be working. :slightly_smiling_face:

**Comment by mrkkrp** [comment]
IIRC we added support for GHCJS on the condition that some of you guys will help maintaining compatibility with GHCJS. If that is not going to work in practice I’ll drop the support as I have enough open source duties already and GHCJS is not something I want to spend time figuring out, sorry.

**Comment by benkolera** [comment]
That's fair @mrkkrp , and I'm sorry that it has taken this long. It has been a week of changing projects at work and a personal family emergency taking up all of my time. But I'm jumping into looking into this now.

**Comment by benkolera** [comment]
Hmmm. I just ran these tests on Ubuntu and they were fine. That's really odd. 

What I do note is that the travis.yml is using node 6.4 and I'm pretty sure my ubuntu has 8.x. There may be something weird going on due to that. I'll cut a branch and see if the error is reproducable for me on travis and whether bumping node fixes things. I took a good look at everything that changed in the new megaparsec and I can't spot anything that'd be crashing things like this. And your new version is working just fine for me in my test reflex app. 

As a future thing, I notice that hvr hasn't built a ghcjs-8.6 in his ppa, yet, so if you are going to drop 8.4 support any time soon we may be in a spot of trouble. I'll ask Herbert whether he just needs help doing that or whether there is a big sad reason why it hasn't appeared yet.

**Comment by benkolera** [comment]
Here's what I know. It's only happening in the tests and it's only happening on travis. It seems to be happening in some threading code and is actually a bug in the generated runtime (probably triggered by hspec) rather than just linking to some bad c or something. 

I have lodged a ghcjs ticket for this, but given this is only happening on travis and appears to be a runtime bug only affecting the tests (my poking things in my test app in a few ways has shown no similar crashes) I'd probably suggest pushing on with the release. It's so weird that travis is the only place that this happens. But I have run the tests a 100 times on my seemingly identical ubuntu vm and poked mmark in a bunch of ways in the ghcjs app that I'm using it in and cannot for the life of me break it. 

The best course of action is for me to figure out what that rts.js function is actually doing and why it may crash, which will take some time. I'll continue using it in the app that I'm developing and if I can make it crash there that may give me some leads, but all the low hanging fruit seem to be gone. 

I'm sorry again for how long this has taken. I legitimately am serious about helping and I'm using this in my project, but the combination of a non-routine ghcjs bug and a messy week made things slow. If you want to kick the mess of ghcjs out of your project I definitely understand, but know that it is definitely appreciated. Thanks for your project and your patience! :slightly_smiling_face:

**Comment by mrkkrp** [comment]
OK, what I'm going to do: I'll allow failures with GHCJS on CI for now. In the meantime I'll proceed with a new release.

**Comment by mrkkrp** [comment]
Or better yet, to make CI run faster I'll comment out the GHCJS test.

**Pull request merged**
